/**
 * AI Design Workflow — MCP Server
 *
 * A Cloudflare Worker that implements the MCP Streamable HTTP transport.
 * Exposes all prompts in the ai-design-workflow repo as MCP tools (dw-*).
 *
 * Prompt registry is read from mcp-server/prompts.json, which is automatically
 * regenerated by a GitHub Action whenever prompts/ changes.
 *
 * Each tool accepts a single `input` argument and returns the completed
 * prompt with {{INPUT}} replaced by the provided value.
 */

export interface Env {
  REPO_OWNER: string;
  REPO_NAME: string;
  REPO_BRANCH: string;
}

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

interface PromptEntry {
  tool: string;
  category: string;
  description: string;
  path: string;
  raw_url: string;
}

interface PromptRegistry {
  generated: string;
  repo: string;
  branch: string;
  prompts: PromptEntry[];
}

interface McpRequest {
  jsonrpc: "2.0";
  id?: string | number | null;
  method: string;
  params?: Record<string, unknown>;
}

interface McpResponse {
  jsonrpc: "2.0";
  id: string | number | null;
  result?: unknown;
  error?: { code: number; message: string };
}

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const CACHE_TTL_SECONDS = 300; // 5 minutes
const MCP_PROTOCOL_VERSION = "2024-11-05";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function rawUrl(env: Env, path: string): string {
  return `https://raw.githubusercontent.com/${env.REPO_OWNER}/${env.REPO_NAME}/${env.REPO_BRANCH}/${path}`;
}

function registryUrl(env: Env): string {
  return rawUrl(env, "mcp-server/prompts.json");
}

/**
 * Fetch a URL with Cloudflare Cache API for short-lived caching.
 * Falls back to a direct fetch on cache miss.
 */
async function cachedFetch(url: string): Promise<string> {
  const cache = caches.default;
  const cacheKey = new Request(url);

  const cached = await cache.match(cacheKey);
  if (cached) {
    return cached.text();
  }

  const response = await fetch(url);
  if (!response.ok) {
    throw new Error(`Failed to fetch ${url}: ${response.status} ${response.statusText}`);
  }

  const body = await response.text();

  // Store in cache with TTL
  const cacheResponse = new Response(body, {
    headers: {
      "Content-Type": "text/plain",
      "Cache-Control": `public, max-age=${CACHE_TTL_SECONDS}`,
    },
  });
  await cache.put(cacheKey, cacheResponse);

  return body;
}

/**
 * Load and parse the prompt registry from prompts.json.
 */
async function loadRegistry(env: Env): Promise<PromptRegistry> {
  const text = await cachedFetch(registryUrl(env));
  return JSON.parse(text) as PromptRegistry;
}

/**
 * Find a prompt entry by tool name.
 */
function findPrompt(registry: PromptRegistry, toolName: string): PromptEntry | undefined {
  return registry.prompts.find((p) => p.tool === toolName);
}

/**
 * Fetch a prompt file and inject the user's input.
 */
async function buildPrompt(entry: PromptEntry, input: string): Promise<string> {
  const template = await cachedFetch(entry.raw_url);
  return template.replace("{{INPUT}}", input);
}

// ---------------------------------------------------------------------------
// MCP response builders
// ---------------------------------------------------------------------------

function mcpResponse(id: string | number | null, result: unknown): McpResponse {
  return { jsonrpc: "2.0", id, result };
}

function mcpError(
  id: string | number | null,
  code: number,
  message: string
): McpResponse {
  return { jsonrpc: "2.0", id, error: { code, message } };
}

function jsonResponse(body: McpResponse, status = 200): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: {
      "Content-Type": "application/json",
      "Access-Control-Allow-Origin": "*",
      "Access-Control-Allow-Methods": "GET, POST, OPTIONS",
      "Access-Control-Allow-Headers": "Content-Type, Authorization, Mcp-Session-Id",
    },
  });
}

function corsPreflightResponse(): Response {
  return new Response(null, {
    status: 204,
    headers: {
      "Access-Control-Allow-Origin": "*",
      "Access-Control-Allow-Methods": "GET, POST, OPTIONS",
      "Access-Control-Allow-Headers": "Content-Type, Authorization, Mcp-Session-Id",
      "Access-Control-Max-Age": "86400",
    },
  });
}

// ---------------------------------------------------------------------------
// MCP method handlers
// ---------------------------------------------------------------------------

function handleInitialize(id: string | number | null): McpResponse {
  return mcpResponse(id, {
    protocolVersion: MCP_PROTOCOL_VERSION,
    capabilities: {
      tools: {},
    },
    serverInfo: {
      name: "ai-design-workflow",
      version: "1.0.0",
    },
  });
}

async function handleToolsList(
  id: string | number | null,
  env: Env
): Promise<McpResponse> {
  const registry = await loadRegistry(env);

  const tools = registry.prompts.map((p) => ({
    name: p.tool,
    description: p.description,
    inputSchema: {
      type: "object",
      properties: {
        input: {
          type: "string",
          description: "The content or context to process with this prompt.",
        },
      },
      required: ["input"],
    },
  }));

  return mcpResponse(id, { tools });
}

async function handleToolsCall(
  id: string | number | null,
  params: Record<string, unknown>,
  env: Env
): Promise<McpResponse> {
  const toolName = params["name"] as string | undefined;
  const args = (params["arguments"] as Record<string, unknown>) ?? {};
  const input = (args["input"] as string | undefined) ?? "";

  if (!toolName) {
    return mcpError(id, -32602, "Missing required parameter: name");
  }

  const registry = await loadRegistry(env);
  const entry = findPrompt(registry, toolName);

  if (!entry) {
    return mcpError(id, -32602, `Unknown tool: ${toolName}`);
  }

  const completedPrompt = await buildPrompt(entry, input);

  return mcpResponse(id, {
    content: [
      {
        type: "text",
        text: completedPrompt,
      },
    ],
  });
}

// ---------------------------------------------------------------------------
// Main fetch handler
// ---------------------------------------------------------------------------

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    const url = new URL(request.url);

    // Health check
    if (url.pathname === "/" || url.pathname === "/health") {
      return new Response(
        JSON.stringify({ status: "ok", server: "ai-design-workflow-mcp" }),
        {
          headers: {
            "Content-Type": "application/json",
            "Access-Control-Allow-Origin": "*",
          },
        }
      );
    }

    // Only handle /mcp endpoint
    if (url.pathname !== "/mcp") {
      return new Response("Not Found", { status: 404 });
    }

    // CORS preflight
    if (request.method === "OPTIONS") {
      return corsPreflightResponse();
    }

    // MCP requires POST
    if (request.method !== "POST") {
      return new Response("Method Not Allowed", { status: 405 });
    }

    // Parse JSON-RPC request
    let mcpReq: McpRequest;
    try {
      mcpReq = (await request.json()) as McpRequest;
    } catch {
      return jsonResponse(mcpError(null, -32700, "Parse error: invalid JSON"), 400);
    }

    const { id = null, method, params = {} } = mcpReq;

    // Route to handler
    try {
      let result: McpResponse;

      switch (method) {
        case "initialize":
          result = handleInitialize(id);
          break;

        case "notifications/initialized":
          // Acknowledgement notification — no response body needed per spec
          return new Response(null, {
            status: 202,
            headers: { "Access-Control-Allow-Origin": "*" },
          });

        case "tools/list":
          result = await handleToolsList(id, env);
          break;

        case "tools/call":
          result = await handleToolsCall(id, params, env);
          break;

        case "ping":
          result = mcpResponse(id, {});
          break;

        default:
          result = mcpError(id, -32601, `Method not found: ${method}`);
      }

      return jsonResponse(result);
    } catch (err) {
      const message = err instanceof Error ? err.message : "Internal server error";
      return jsonResponse(mcpError(id, -32603, message), 500);
    }
  },
};
